lib1 segment at 2087h
	funct01 label far
	org 01fch
	funct02 label far
lib1 ends

lib2 segment at 20c8h
	org 001ch
	funct03 label far

	org 0043h
	funct04 label far

	org 01a7h
	funct05 label far

	org 01eeh
	funct06 label far
lib2 ends

lib3 segment at 2110h
	org 02edh
	funct07 label far

	org 02f7h
	funct08 label far

	org 0402h
	funct09 label far
lib3 ends

lib4 segment at 2158h
	org 0306h
	funct10 label far
lib4 ends

lib5 segment at 24c9h
	org 0fh
	funct11 label far
lib5 ends
