data segment at 4000h
	org 0ach
	data01 db ?
	org 0b2h
	data02 dw ?
	org 0b6h
	data03 db ?
	org 0b8h
	data04 db ?
	org 0bch
	data05 dw ?
	org 0c0h
	data06 dw ?
	data07 db ?	
	org 0d8h
	data08 db ?
	org 0dch
	data09 dw ?
	org 0e0h
	data10 dw ?
	data11 db ?
	org 0e6h
	data12 db ?
	org 0ech
	data13 db ?
	org 0eeh
	data14 db ?
	org 0f0h
	data15 db ?
	org 0f2h
	data16 dw ?
	org 0f4h
	data17 dw ?
	data18 dw ?
	data19 dw ?
	data20 dw ?
	data21 dw ?

	org 10ah
	data22 db ?
	org 138h
	data23 db ?

	org 23ch
	data24 db ?
	org 286h
	data25 db ?
	org 288h
	data26 db ?
	org 296h
	data27 dw ?
	org 29ah
	data28 dw ?
	data29 dw ?
	org 2aeh
	data30 db ?

	org 376h
	data31 dw ?
	org 386h
	data32 dw ?
	org 38eh
	data33 db ?
	org 390h
	data34 db ?
	org 3a6h
	data35 dw ?
	org 3aah
	data36 dw ?
	org 3b6h
	data37 dw ?
	data38 dw ?
	org 3bah
	data39 dw ?
	org 3c2h
	data40 dw ?
	data41 dw ?
	org 3ceh
	data42 dw ?

	org 0bdch
	data43 db ?

	org 17d2h
	data44 db ?
	data45 db ?

	org 68f4h
	data46 dw ?
data ends
